"""
Claustor AI — PDF Report Generator
===================================
Generates portfolio risk and counterparty exposure reports.
"""
import io
from datetime import datetime, date, timedelta
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_RIGHT

BRAND_PRIMARY = colors.HexColor("#5B4BFF")
BRAND_DARK = colors.HexColor("#1C1B2E")
RISK_COLORS = {
    "critical": colors.HexColor("#991B1B"),
    "high":     colors.HexColor("#DC2626"),
    "medium":   colors.HexColor("#D97706"),
    "low":      colors.HexColor("#16A34A"),
}


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        "BrandTitle", parent=styles["Heading1"],
        fontSize=22, textColor=BRAND_DARK, spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        "BrandSubtitle", parent=styles["Normal"],
        fontSize=11, textColor=colors.HexColor("#64748B"), spaceAfter=16,
    ))
    styles.add(ParagraphStyle(
        "SectionHead", parent=styles["Heading2"],
        fontSize=14, textColor=BRAND_PRIMARY, spaceBefore=16, spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "MetricLabel", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#64748B"),
    ))
    styles.add(ParagraphStyle(
        "MetricValue", parent=styles["Normal"],
        fontSize=16, textColor=BRAND_DARK, fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        "CellText", parent=styles["Normal"],
        fontSize=9, leading=12,
    ))
    styles.add(ParagraphStyle(
        "CellBold", parent=styles["Normal"],
        fontSize=9, leading=12, fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        "Footer", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#94A3B8"), alignment=TA_CENTER,
    ))
    return styles


def _format_value(v, currency="USD"):
    if not v:
        return "—"
    sym = "₹" if currency == "INR" else "$"
    if v >= 10_000_000:
        return f"{sym}{v/1_000_000:,.1f}M"
    if v >= 100_000:
        return f"{sym}{v/1_000:,.0f}K"
    return f"{sym}{v:,.0f}"


def _risk_text(level):
    return f'<font color="{RISK_COLORS.get(level, colors.gray)}">{(level or "—").upper()}</font>'


def _header_table(data, col_widths):
    """Styled table with brand header row."""
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), BRAND_PRIMARY),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTSIZE",    (0, 0), (-1, 0), 9),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 1), (-1, -1), 9),
        ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("PADDING",     (0, 0), (-1, -1), 6),
        ("VALIGN",      (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    return t


def generate_portfolio_risk_report(contracts, clauses_by_contract, obligations) -> io.BytesIO:
    """
    Generate a comprehensive portfolio risk report PDF.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                            leftMargin=1.5*cm, rightMargin=1.5*cm)
    s = _styles()
    story = []
    today = date.today()

    # ── Title ──
    story.append(Paragraph("Portfolio Risk Report", s["BrandTitle"]))
    story.append(Paragraph(
        f"Generated by Claustor AI on {today.strftime('%B %d, %Y')}", s["BrandSubtitle"]))
    story.append(HRFlowable(width="100%", color=BRAND_PRIMARY, thickness=2))
    story.append(Spacer(1, 0.5*cm))

    # ── Executive Summary ──
    total = len(contracts)
    total_value = sum(c.contract_value or 0 for c in contracts)
    high_risk = sum(1 for c in contracts if c.risk_level in ("high", "critical"))
    medium_risk = sum(1 for c in contracts if c.risk_level == "medium")
    low_risk = sum(1 for c in contracts if c.risk_level == "low")
    expiring_90 = sum(1 for c in contracts
                      if c.expiry_date and today <= c.expiry_date <= today + timedelta(days=90))
    avg_risk = sum(c.risk_score or 0 for c in contracts) / max(total, 1)

    story.append(Paragraph("Executive Summary", s["SectionHead"]))
    summary_data = [
        ["Metric", "Value"],
        ["Total Contracts", str(total)],
        ["Portfolio Value", _format_value(total_value)],
        ["Average Risk Score", f"{avg_risk:.1f} / 100"],
        ["High/Critical Risk Contracts", f"{high_risk} ({high_risk*100//max(total,1)}%)"],
        ["Medium Risk Contracts", f"{medium_risk}"],
        ["Low Risk Contracts", f"{low_risk}"],
        ["Expiring in 90 Days", f"{expiring_90}"],
        ["Total Obligations", str(len(obligations))],
    ]
    story.append(_header_table(summary_data, [6*cm, 12*cm]))
    story.append(Spacer(1, 0.5*cm))

    # ── Risk Distribution ──
    story.append(Paragraph("Risk Distribution", s["SectionHead"]))
    risk_data = [["Risk Level", "Count", "% of Portfolio", "Total Value"]]
    for level in ["critical", "high", "medium", "low"]:
        count = sum(1 for c in contracts if c.risk_level == level)
        value = sum(c.contract_value or 0 for c in contracts if c.risk_level == level)
        pct = f"{count*100//max(total,1)}%"
        risk_data.append([level.upper(), str(count), pct, _format_value(value)])
    story.append(_header_table(risk_data, [4*cm, 3*cm, 4*cm, 7*cm]))
    story.append(Spacer(1, 0.5*cm))

    # ── High Risk Contracts Detail ──
    high_risk_contracts = [c for c in contracts if c.risk_level in ("high", "critical")]
    if high_risk_contracts:
        story.append(Paragraph("High Risk Contracts — Detail", s["SectionHead"]))
        for c in sorted(high_risk_contracts, key=lambda x: x.risk_score or 0, reverse=True):
            contract_data = [
                ["Field", "Value"],
                ["Contract", c.title or "—"],
                ["Counterparty", c.counterparty or "—"],
                ["Risk Score", f"{c.risk_score or 0:.0f} / 100"],
                ["Risk Level", (c.risk_level or "—").upper()],
                ["Value", _format_value(c.contract_value, c.contract_currency)],
                ["Expiry", str(c.expiry_date) if c.expiry_date else "—"],
                ["Auto-Renewal", "Yes" if c.auto_renewal else "No"],
            ]
            # Add top clauses
            c_clauses = clauses_by_contract.get(str(c.id), [])
            high_clauses = [cl for cl in c_clauses if cl.risk_level in ("high", "critical")]
            if high_clauses:
                for i, cl in enumerate(high_clauses[:5]):
                    contract_data.append([
                        f"Risk Clause {i+1}",
                        f"{cl.clause_type}: {(cl.title or '')[:60]}"
                    ])

            story.append(_header_table(contract_data, [5*cm, 13*cm]))
            story.append(Spacer(1, 0.3*cm))

    # ── Upcoming Expirations ──
    expiring = [c for c in contracts if c.expiry_date and c.expiry_date <= today + timedelta(days=180)]
    expiring.sort(key=lambda c: c.expiry_date)
    if expiring:
        story.append(PageBreak())
        story.append(Paragraph("Upcoming Expirations (180 Days)", s["SectionHead"]))
        exp_data = [["Contract", "Counterparty", "Expiry", "Days Left", "Value", "Risk"]]
        for c in expiring:
            days_left = (c.expiry_date - today).days
            urgency = "OVERDUE" if days_left < 0 else f"{days_left}d"
            exp_data.append([
                (c.title or "—")[:35],
                (c.counterparty or "—")[:25],
                str(c.expiry_date),
                urgency,
                _format_value(c.contract_value, c.contract_currency),
                (c.risk_level or "—").upper(),
            ])
        story.append(_header_table(exp_data, [5*cm, 4*cm, 2.5*cm, 2*cm, 2.5*cm, 2*cm]))

    # ── Obligations Summary ──
    if obligations:
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph("Obligation Summary", s["SectionHead"]))
        overdue = sum(1 for o in obligations if o.due_date and o.due_date < today and o.status != "completed")
        pending = sum(1 for o in obligations if o.status != "completed")
        completed = sum(1 for o in obligations if o.status == "completed")
        ob_data = [
            ["Metric", "Count"],
            ["Total Obligations", str(len(obligations))],
            ["Overdue", str(overdue)],
            ["Pending", str(pending)],
            ["Completed", str(completed)],
        ]
        story.append(_header_table(ob_data, [6*cm, 12*cm]))

    # ── Footer ──
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#E2E8F0"), thickness=0.5))
    story.append(Paragraph(
        f"Claustor AI — Confidential | Generated {today.strftime('%Y-%m-%d %H:%M')} UTC",
        s["Footer"]))

    doc.build(story)
    buffer.seek(0)
    return buffer


def generate_counterparty_exposure_report(groups, total_contracts, portfolio_value) -> io.BytesIO:
    """
    Generate a counterparty exposure report PDF.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                            leftMargin=1.5*cm, rightMargin=1.5*cm)
    s = _styles()
    story = []
    today = date.today()

    # ── Title ──
    story.append(Paragraph("Counterparty Exposure Report", s["BrandTitle"]))
    story.append(Paragraph(
        f"Generated by Claustor AI on {today.strftime('%B %d, %Y')}", s["BrandSubtitle"]))
    story.append(HRFlowable(width="100%", color=BRAND_PRIMARY, thickness=2))
    story.append(Spacer(1, 0.5*cm))

    # ── Executive Summary ──
    story.append(Paragraph("Executive Summary", s["SectionHead"]))
    summary_data = [
        ["Metric", "Value"],
        ["Total Counterparties", str(len(groups))],
        ["Total Contracts", str(total_contracts)],
        ["Portfolio Value", _format_value(portfolio_value)],
        ["High Risk Counterparties", str(sum(1 for g in groups if g["max_risk_level"] in ("high", "critical")))],
        ["Counterparties with Expiring Contracts", str(sum(1 for g in groups if g["expiring_soon"] > 0))],
    ]
    story.append(_header_table(summary_data, [7*cm, 11*cm]))
    story.append(Spacer(1, 0.5*cm))

    # ── Exposure by Counterparty ──
    story.append(Paragraph("Exposure by Counterparty", s["SectionHead"]))
    exp_data = [["Counterparty", "Contracts", "Total Value", "Avg Risk", "Max Risk", "Expiring"]]
    for g in groups:
        exp_data.append([
            g["counterparty"][:30],
            str(g["contract_count"]),
            _format_value(g["total_value"], g.get("currency")),
            f"{g['avg_risk_score']:.0f}",
            (g["max_risk_level"] or "—").upper(),
            str(g["expiring_soon"]),
        ])
    story.append(_header_table(exp_data, [5*cm, 2*cm, 3*cm, 2*cm, 2*cm, 2*cm]))
    story.append(Spacer(1, 0.5*cm))

    # ── Top Exposure Detail ──
    top_groups = [g for g in groups if g["total_value"] > 0][:5]
    if top_groups:
        story.append(Paragraph("Top 5 Counterparties — Contract Detail", s["SectionHead"]))
        for g in top_groups:
            story.append(Paragraph(
                f'<b>{g["counterparty"]}</b> — {g["contract_count"]} contracts, '
                f'{_format_value(g["total_value"], g.get("currency"))} exposure',
                s["Normal"]))
            story.append(Spacer(1, 0.2*cm))

            detail_data = [["Contract", "Type", "Value", "Risk", "Expiry"]]
            for c in g["contracts"]:
                detail_data.append([
                    (c["title"] or "—")[:35],
                    c.get("contract_type") or "—",
                    _format_value(c.get("contract_value"), c.get("contract_currency")),
                    (c.get("risk_level") or "—").upper(),
                    c.get("expiry_date") or "—",
                ])
            story.append(_header_table(detail_data, [5.5*cm, 3*cm, 3*cm, 2*cm, 3*cm]))
            story.append(Spacer(1, 0.4*cm))

    # ── Risk Concentration ──
    story.append(PageBreak())
    story.append(Paragraph("Risk Concentration Analysis", s["SectionHead"]))
    story.append(Paragraph(
        "Counterparties ranked by concentration risk — "
        "single counterparty representing a large share of portfolio value.",
        s["Normal"]))
    story.append(Spacer(1, 0.3*cm))

    conc_data = [["Counterparty", "Value", "% of Portfolio", "Risk Assessment"]]
    for g in groups:
        if portfolio_value > 0:
            pct = g["total_value"] * 100 / portfolio_value
        else:
            pct = 0
        assessment = "CRITICAL" if pct > 50 else "HIGH" if pct > 25 else "MODERATE" if pct > 10 else "LOW"
        conc_data.append([
            g["counterparty"][:30],
            _format_value(g["total_value"], g.get("currency")),
            f"{pct:.1f}%",
            assessment,
        ])
    story.append(_header_table(conc_data, [5*cm, 3.5*cm, 3.5*cm, 4*cm]))

    # ── Footer ──
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#E2E8F0"), thickness=0.5))
    story.append(Paragraph(
        f"Claustor AI — Confidential | Generated {today.strftime('%Y-%m-%d %H:%M')} UTC",
        s["Footer"]))

    doc.build(story)
    buffer.seek(0)
    return buffer
