apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: claustor-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: claustor-api@claustor-prod.iam.gserviceaccount.com
      containers:
        - image: REGION-docker.pkg.dev/claustor-prod/claustor/api:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
          envFrom:
            - secretRef:
                name: claustor-env
